name: fts_benchmark
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/sjhorn/fts_benchmark

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  lunr: ^2.3.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
